### PR TITLE
Update Ch. 22

### PR DESCRIPTION
**Pull request by JeffreyRStevens**

### CODE REVIEW

**Comment by jonthegeek** [comment]
@JeffreyRStevens @lgibson7 is reviewing these ones. I recommend rendering local with ctrl-shift-k and presenting from that. Is there a particular reason that that won't work?

**Comment by JeffreyRStevens** [comment]
I can do that. It's just nice if everyone can access the updated slides themselves in case they want to go back to look at something without interrupting the presenter or click links themselves etc. 
Thanks.

**Comment by lgibson7** [comment]
Apologies. I hadn't set my notifications to watch all activity in this particular repo.

**Review by lgibson7 — APPROVED** [review]
Looks good. Thanks @JeffreyRStevens!

**Pull request merged**
