### PR TITLE
chapter6

### PR DESCRIPTION
**Pull request by Fgazzelloni**

### CODE REVIEW

**Review by jonthegeek — COMMENTED** [review]
Always try to build the book locally (ctrl-shift-b) before submitting the PR. This failed with an error that told me what to fix (I had to make a chunk name unique).

Which course does this example come from on coursera? The link is to a specialization, with 3 courses. Is anything copy/pasted from that course, or is it just the general idea from that course?

**Comment by Fgazzelloni** [comment]
ok

**Comment by Fgazzelloni** [comment]
I'll be more specific in the book club session.

**Comment by Fgazzelloni** [comment]
The function is the main function used in all of the courses in the specialization.

**Comment by Fgazzelloni** [comment]
I knit it and it compiled. While if I use ctr+shift+b it says about an error in processing the book.

**Review by jonthegeek — APPROVED** [review]
FYI ctrl-shift-b is equivalent to what the system runs. If it doesn't work, the system will not be able to build the book, and your PR will be rejected. Pay attention to what error messages tell you to fix when that happens (in this case the chunk labeled "c01" was duplicated in another chapter, so I renamed it "06-c01").

I removed the unused package. Thanks for letting me know it wasn't used! Try to trim out any unused packages, it makes the builds run faster and reduces issues with other people using the notes!

**Pull request merged**
